name: jikkou
description: Update Kafka Environment
inputs:
  environment-file:  # id of input
    description: Environment File
    required: true
runs:
  using: composite
  steps:
    - name: update-topics
      run: source ${{ inputs.environment-file }} && jikkou create -f gitops/topics
      shell: bash
    - name: update-acls
      run: source ${{ inputs.environment-file }} && jikkou create -f gitops/acls 
      shell: bash
