apiVersion: kafka.jikkou.io/v1beta2
kind: KafkaTopicList
items:
  - metadata:
      name: alpt.{{ system.env.ENV }}.client-topic-1
    spec:
      partitions: 6
      replicationFactor: 1
      configs:
        cleanup.policy: compact

  - metadata:
      name: alpt.{{ system.env.ENV }}.client-topic-2
    spec:
      partitions: 4
      replicationFactor: 1
      configs:
        cleanup.policy: delete
        retention.ms: 2419200000





        