---
apiVersion: kafka.jikkou.io/v1beta2
kind: KafkaPrincipalAuthorization
metadata:
  name: User:{{ system.env.PRODUCER_USER }}
spec:
  acls:
    - resource:
        type: topic
        pattern: alpt.{{ system.env.ENV }}.raw.my-first-topic
        patternType: LITERAL
      type: ALLOW
      operations: [ WRITE, DESCRIBE, DESCRIBE_CONFIGS ]
      host: '*'
    - resource:
        type: topic
        pattern: alpt.{{ system.env.ENV }}.raw.my-second-topic
        patternType: LITERAL
      type: ALLOW
      operations: [ WRITE, DESCRIBE, DESCRIBE_CONFIGS ]
      host: '*'
    - resource:
        type: topic
        pattern: alpt.{{ system.env.ENV }}.raw.my-third-topic
        patternType: LITERAL
      type: ALLOW
      operations: [ WRITE, DESCRIBE, DESCRIBE_CONFIGS ]
      host: '*'
    - resource:
        type: topic
        pattern: alpt.{{ system.env.ENV }}.raw.my-fourth-topic
        patternType: LITERAL
      type: ALLOW
      operations: [ WRITE, DESCRIBE, DESCRIBE_CONFIGS ]
      host: '*'