name: development deploy
on: 
  push:
    branches: ['master']
    # paths:
    #   - 'gitops/**'
jobs:
  apply-jikkou:
    runs-on: local-altice
    environment: 
      name: DEV
      url: http://localhost:8087
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Check ENV
        run: source ./gitops/environment/dev.sh && echo $ENV
      - name: update-topics
        run: source ./gitops/environment/dev.sh && jikkou create -f gitops/topics
      - name: update-acls
        run: source ./gitops/environment/dev.sh && jikkou create -f gitops/acls 
