name: jikkou_test
on: 
  push:
    paths:
      - 'gitops/**'
jobs:
  apply-jikkou:
    runs-on: local-altice
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: update-topics
        run: jikkou apply -f gitops/kafka-topics.yaml
      - name: update-acls
        run: jikkou apply -f gitops/kafka-acls.yaml
