# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Create and publish a Docker image

on:
  push:
    branches: ['master']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag ${{ env.REGISTRY }}/jnmarques/${{ env.IMAGE_NAME }}:latest
          docker push ${{ env.REGISTRY }}/jnmarques/${{ env.IMAGE_NAME }}:latest
  pull-image-and-reload:
    runs-on: lynxmind-workstation
    permissions:
      packages: read
      contents: read
    
    steps:
      - name: Docker login
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Pull and Run image
        run: |
          docker pull ${{ env.REGISTRY }}/jnmarques/${{ env.IMAGE_NAME }}:latest
          docker run ${{ env.REGISTRY }}/jnmarques/${{ env.IMAGE_NAME }}:latest
